version: "3.7"

services:
  proxy:
    image: nginx:1.21.4
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
      - ./.htpasswd:/etc/nginx/.htpasswd
    ports:
      - "8080:8080"

  2fauth:
    image: 2fauth/2fauth:dev
    environment:
      - APP_LOG_LEVEL=debug
      #- PROXY_LOGOUT_URL=null
      # Authentication settings
      # The default authentication guard
      # Supported:
      #   'web-guard' : The Laravel built-in auth system (default if nulled)
      #   'reverse-proxy-guard' : When 2FAuth is deployed behind a reverse-proxy that handle authentication
      # WARNING
      # When using 'reverse-proxy-guard' 2FAuth only look for the dedicated headers and skip all other built-in
      # authentication checks. That means your proxy is fully responsible of the authentication process, 2FAuth will
      # trust him as long as headers are presents.
      - AUTHENTICATION_GUARD=reverse-proxy-guard
      # Name of the HTTP headers sent by the reverse proxy that identifies the authenticated user at proxy level.
      # Check your proxy documentation to find out how these headers are named (i.e 'REMOTE_USER', 'REMOTE_EMAIL', etc...)
      # (only relevant when AUTHENTICATION_GUARD is set to 'reverse-proxy-guard')
      - AUTH_PROXY_HEADER_FOR_USER=HTTP_REMOTE_USER
      - AUTH_PROXY_HEADER_FOR_EMAIL=HTTP_REMOTE_EMAIL
      # Use this setting to declare trusted proxied.
      # Supported:
      #   '*': to trust any proxy
      #   A comma separated IP list: The list of proxies IP to trust
      - TRUSTED_PROXIES=*
