version: '3.5'

services:
  2fauth:
    image: 2fauth/2fauth:latest
    volumes:
      - 2fauth_storage:/var/www/html/storage
    env_file: .env
    ports:
      - 8000:8000
    depends_on:
      - 2fauth-db
    networks:
      - 2fauth

  2fauth-db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - 2fauth_database:/var/lib/mysql
    networks:
      - 2fauth

volumes:
   2fauth_storage:
   2fauth_database:

networks:
  2fauth:
    driver: bridge
